services:
  odoo_desa:
    image: odoo:17
    ports:
      - "8079:8069"
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_DB=postgres
    volumes:
      - odoo-data:/var/lib/odoo
      - ./addons:/mnt/extra-addons
      - ./odoo.conf:/etc/odoo/odoo.conf
    
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_DB=postgres
    volumes:
      - ./db/data:/var/lib/postgresql/data
    ports:
      - 5555:5432

volumes:
  odoo-data:
